apiVersion: v1
kind: Service
metadata:
  name: veg-service
  namespace: dharani-ns
spec:
  type: LoadBalancer
  selector:
    app: veg
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
